
export const GET_ALL_PERSONS_REQUEST = 'GET_PERSONS_REQUEST';
export const GET_ALL_PERSONS_SUCCESS = 'GET_PERSONS_SUCCESS';
export const GET_ALL_PERSONS_FAILURE = 'GET_PERSONS_FAILURE';

export const CREATE_DEBT_REQUEST = 'CREATE_DEBT_REQUEST';
export const CREATE_DEBT_SUCCESS = 'CREATE_DEBT_SUCCESS';
export const CREATE_DEBT_FAILURE = 'CREATE_DEBT_FAILURE';