
export const GET_ALL_PERSONS_REQUEST = 'GET_ALL_PERSONS_REQUEST';
export const GET_ALL_PERSONS_SUCCESS = 'GET_ALL_PERSONS_SUCCESS';
export const GET_ALL_PERSONS_FAILURE = 'GET_ALL_PERSONS_FAILURE';

export const CREATE_DEBT_REQUEST = 'CREATE_DEBT_REQUEST';
export const CREATE_DEBT_SUCCESS = 'CREATE_DEBT_SUCCESS';
export const CREATE_DEBT_FAILURE = 'CREATE_DEBT_FAILURE';

export const GET_DEBTS_REQUEST = 'GET_DEBTS_REQUEST';
export const GET_DEBTS_SUCCESS = 'GET_DEBTS_SUCCESS';
export const GET_DEBTS_FAILURE = 'GET_DEBTS_FAILURE';

export const DELETE_DEBT_REQUEST = 'DELETE_DEBT_REQUEST';
export const DELETE_DEBT_SUCCESS = 'DELETE_DEBT_SUCCESS';
export const DELETE_DEBT_FAILURE = 'DELETE_DEBT_FAILURE';

export const GET_DEBT_REQUEST = 'GET_DEBT_REQUEST';
export const GET_DEBT_SUCCESS = 'GET_DEBT_SUCCESS';
export const GET_DEBT_FAILURE = 'GET_DEBT_FAILURE';

export const EDIT_DEBT_REQUEST = 'EDIT_DEBT_REQUEST';
export const EDIT_DEBT_SUCCESS = 'EDIT_DEBT_SUCCESS';
export const EDIT_DEBT_FAILURE = 'EDIT_DEBT_FAILURE';

export const GET_STATISTICS_REQUEST = 'GET_STATISTICS_REQUEST';
export const GET_STATISTICS_FAILURE = 'GET_STATISTICS_FAILURE';
export const GET_STATISTICS_SUCCESS = 'GET_STATISTICS_SUCCESS';

export const FETCHING = 'FETCHING';
export const FETCHING_RESET = 'FETCHING_RESET';
export const FAILURE = 'FAILURE';

export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_ERROR = 'RESET_ERROR';
export const RESET_DEBT_DELETED = 'RESET_DEBT_DELETED';