export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const AUTHENTICATED = 'AUTHENTICATED';
export const IS_AUTHENTICATED_REQUEST = 'IS_AUTHENTICATED_REQUEST';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const SIGN_UP_SUCCESS_RESET = 'SIGN_UP_SUCCESS_RESET';
export const SIGN_UP_ERROR_RESET = 'SIGN_UP_ERROR_RESET';

export const LOGIN_ERROR_RESET = 'LOGIN_ERROR_RESET';