import configureMockStore from "redux-mock-store";

const mockStore = configureMockStore();
export const store = mockStore({persons: { persons :[ {
                Author_id: "62",
                first_name: "Ulix",
                myDebtSummDol: -100,
                myDebtSummEur: -100,
                myDebtSummRub: -100,
                name: "Ulix Turner",
                second_name: "Turner",
                theirDebtSummDol: 100,
                theirDebtSummEur: 100,
                theirDebtSummRub: 100,
                tid: "1",
            },
            {
                Author_id: "62",
                first_name: "Ophelia",
                myDebtSummDol: -200,
                myDebtSummEur: -200,
                myDebtSummRub: -200,
                name: "Ophelia LaCroix",
                second_name: "LaCroix",
                theirDebtSummDol: 0,
                theirDebtSummEur: 0,
                theirDebtSummRub: 0,
                tid: "2",
            },
            {
                Author_id: "62",
                first_name: "Sommer",
                myDebtSummDol: -300,
                myDebtSummEur: -300,
                myDebtSummRub: -300,
                name: "Sommer Jones",
                second_name: "Jones",
                theirDebtSummDol: 100,
                theirDebtSummEur: 100,
                theirDebtSummRub: 100,
                tid: "3",
            },
            {
                Author_id: "62",
                first_name: "Samael",
                myDebtSummDol: -150,
                myDebtSummEur: -150,
                myDebtSummRub: -150,
                name: "Samael Hopkins",
                second_name: "Hopkins",
                theirDebtSummDol: 400,
                theirDebtSummEur: 400,
                theirDebtSummRub: 400,
                tid: "4",
            },
            {
                Author_id: "62",
                first_name: "Euripides",
                myDebtSummDol: 0,
                myDebtSummEur: 0,
                myDebtSummRub: 0,
                name: "Euripides Ancient",
                second_name: "Ancient",
                theirDebtSummDol: 100,
                theirDebtSummEur: 100,
                theirDebtSummRub: 100,
                tid: "5",
            },
            {
                Author_id: "62",
                first_name: "Doctor",
                myDebtSummDol: -1000,
                myDebtSummEur: -1000,
                myDebtSummRub: -1000,
                name: "Doctor McMourning",
                second_name: "McMourning",
                theirDebtSummDol: 0,
                theirDebtSummEur: 0,
                theirDebtSummRub: 0,
                tid: "6",
            },
            {
                Author_id: "62",
                first_name: "Marcus",
                myDebtSummDol: -100,
                myDebtSummEur: -100,
                myDebtSummRub: -100,
                name: "Marcus TheWild",
                second_name: "TheWild",
                theirDebtSummDol: 500,
                theirDebtSummEur: 500,
                theirDebtSummRub: 500,
                tid: "7",
            },
            {
                Author_id: "62",
                first_name: "Sonnia",
                myDebtSummDol: -1100,
                myDebtSummEur: -1100,
                myDebtSummRub: -1100,
                name: "Sonnia Criid",
                second_name: "Criid",
                theirDebtSummDol: 0,
                theirDebtSummEur: 0,
                theirDebtSummRub: 0,
                tid: "8",
            },
        ]}});
