export const PERSON_FETCHING = 'PERSON_FETCHING';
export const GET_PERSONS_REQUEST = 'GET_PERSONS_REQUEST';
export const GET_PERSONS_SUCCESS = 'GET_PERSONS_SUCCESS';
export const GET_PERSONS_FAILURE = 'GET_PERSONS_FAILURE';

export const EDIT_PERSON_REQUEST = 'EDIT_PERSON_REQUEST';
export const EDIT_PERSON_SUCCESS = 'EDIT_PERSON_SUCCESS';
export const EDIT_PERSON_FAILURE = 'EDIT_PERSON_FAILURE';

export const DELETE_PERSON_REQUEST = 'DELETE_PERSON_REQUEST';
export const DELETE_PERSON_SUCCESS = 'DELETE_PERSON_SUCCESS';
export const DELETE_PERSON_FAILURE = 'DELETE_PERSON_FAILURE';

export const LOAD_PERSONS_SUCCESS = 'LOAD_PERSONS_SUCCESS';

export const CREATE_PERSON_REQUEST = 'CREATE_PERSON_REQUEST';
export const CREATE_PERSON_SUCCESS = 'CREATE_PERSON_SUCCESS';
export const CREATE_PERSON_FAILURE = 'CREATE_PERSON_FAILURE';

export const GET_PERSON_SUCCESS = 'GET_PERSON_SUCCESS';
export const GET_PERSON_FAILURE = 'GET_PERSON_FAILURE';
export const GET_PERSON_REQUEST = 'GET_PERSON_REQUEST';

export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_ERROR = 'RESET_ERROR';